/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRegulationStandardsRouteImport } from './routes/api/regulation-standards'
import { Route as ApiEvaluationAttributesRouteImport } from './routes/api/evaluation-attributes'
import { Route as ApiBusinessProcessesRouteImport } from './routes/api/business-processes'
import { Route as ApiAuditAssessmentsRouteImport } from './routes/api/audit-assessments'
import { Route as ApiBusinessProcessesIdIndexRouteImport } from './routes/api/business-processes/$id/index'
import { Route as ApiAuditAssessmentsIdValuesRouteImport } from './routes/api/audit-assessments/$id/values'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegulationStandardsRoute = ApiRegulationStandardsRouteImport.update({
  id: '/api/regulation-standards',
  path: '/api/regulation-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluationAttributesRoute = ApiEvaluationAttributesRouteImport.update({
  id: '/api/evaluation-attributes',
  path: '/api/evaluation-attributes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusinessProcessesRoute = ApiBusinessProcessesRouteImport.update({
  id: '/api/business-processes',
  path: '/api/business-processes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditAssessmentsRoute = ApiAuditAssessmentsRouteImport.update({
  id: '/api/audit-assessments',
  path: '/api/audit-assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusinessProcessesIdIndexRoute =
  ApiBusinessProcessesIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => ApiBusinessProcessesRoute,
  } as any)
const ApiAuditAssessmentsIdValuesRoute =
  ApiAuditAssessmentsIdValuesRouteImport.update({
    id: '/$id/values',
    path: '/$id/values',
    getParentRoute: () => ApiAuditAssessmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/audit-assessments': typeof ApiAuditAssessmentsRouteWithChildren
  '/api/business-processes': typeof ApiBusinessProcessesRouteWithChildren
  '/api/evaluation-attributes': typeof ApiEvaluationAttributesRoute
  '/api/regulation-standards': typeof ApiRegulationStandardsRoute
  '/api/audit-assessments/$id/values': typeof ApiAuditAssessmentsIdValuesRoute
  '/api/business-processes/$id/': typeof ApiBusinessProcessesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/audit-assessments': typeof ApiAuditAssessmentsRouteWithChildren
  '/api/business-processes': typeof ApiBusinessProcessesRouteWithChildren
  '/api/evaluation-attributes': typeof ApiEvaluationAttributesRoute
  '/api/regulation-standards': typeof ApiRegulationStandardsRoute
  '/api/audit-assessments/$id/values': typeof ApiAuditAssessmentsIdValuesRoute
  '/api/business-processes/$id': typeof ApiBusinessProcessesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/audit-assessments': typeof ApiAuditAssessmentsRouteWithChildren
  '/api/business-processes': typeof ApiBusinessProcessesRouteWithChildren
  '/api/evaluation-attributes': typeof ApiEvaluationAttributesRoute
  '/api/regulation-standards': typeof ApiRegulationStandardsRoute
  '/api/audit-assessments/$id/values': typeof ApiAuditAssessmentsIdValuesRoute
  '/api/business-processes/$id/': typeof ApiBusinessProcessesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/audit-assessments'
    | '/api/business-processes'
    | '/api/evaluation-attributes'
    | '/api/regulation-standards'
    | '/api/audit-assessments/$id/values'
    | '/api/business-processes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/audit-assessments'
    | '/api/business-processes'
    | '/api/evaluation-attributes'
    | '/api/regulation-standards'
    | '/api/audit-assessments/$id/values'
    | '/api/business-processes/$id'
  id:
    | '__root__'
    | '/'
    | '/api/audit-assessments'
    | '/api/business-processes'
    | '/api/evaluation-attributes'
    | '/api/regulation-standards'
    | '/api/audit-assessments/$id/values'
    | '/api/business-processes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuditAssessmentsRoute: typeof ApiAuditAssessmentsRouteWithChildren
  ApiBusinessProcessesRoute: typeof ApiBusinessProcessesRouteWithChildren
  ApiEvaluationAttributesRoute: typeof ApiEvaluationAttributesRoute
  ApiRegulationStandardsRoute: typeof ApiRegulationStandardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/regulation-standards': {
      id: '/api/regulation-standards'
      path: '/api/regulation-standards'
      fullPath: '/api/regulation-standards'
      preLoaderRoute: typeof ApiRegulationStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluation-attributes': {
      id: '/api/evaluation-attributes'
      path: '/api/evaluation-attributes'
      fullPath: '/api/evaluation-attributes'
      preLoaderRoute: typeof ApiEvaluationAttributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/business-processes': {
      id: '/api/business-processes'
      path: '/api/business-processes'
      fullPath: '/api/business-processes'
      preLoaderRoute: typeof ApiBusinessProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-assessments': {
      id: '/api/audit-assessments'
      path: '/api/audit-assessments'
      fullPath: '/api/audit-assessments'
      preLoaderRoute: typeof ApiAuditAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/business-processes/$id/': {
      id: '/api/business-processes/$id/'
      path: '/$id'
      fullPath: '/api/business-processes/$id/'
      preLoaderRoute: typeof ApiBusinessProcessesIdIndexRouteImport
      parentRoute: typeof ApiBusinessProcessesRoute
    }
    '/api/audit-assessments/$id/values': {
      id: '/api/audit-assessments/$id/values'
      path: '/$id/values'
      fullPath: '/api/audit-assessments/$id/values'
      preLoaderRoute: typeof ApiAuditAssessmentsIdValuesRouteImport
      parentRoute: typeof ApiAuditAssessmentsRoute
    }
  }
}

interface ApiAuditAssessmentsRouteChildren {
  ApiAuditAssessmentsIdValuesRoute: typeof ApiAuditAssessmentsIdValuesRoute
}

const ApiAuditAssessmentsRouteChildren: ApiAuditAssessmentsRouteChildren = {
  ApiAuditAssessmentsIdValuesRoute: ApiAuditAssessmentsIdValuesRoute,
}

const ApiAuditAssessmentsRouteWithChildren =
  ApiAuditAssessmentsRoute._addFileChildren(ApiAuditAssessmentsRouteChildren)

interface ApiBusinessProcessesRouteChildren {
  ApiBusinessProcessesIdIndexRoute: typeof ApiBusinessProcessesIdIndexRoute
}

const ApiBusinessProcessesRouteChildren: ApiBusinessProcessesRouteChildren = {
  ApiBusinessProcessesIdIndexRoute: ApiBusinessProcessesIdIndexRoute,
}

const ApiBusinessProcessesRouteWithChildren =
  ApiBusinessProcessesRoute._addFileChildren(ApiBusinessProcessesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuditAssessmentsRoute: ApiAuditAssessmentsRouteWithChildren,
  ApiBusinessProcessesRoute: ApiBusinessProcessesRouteWithChildren,
  ApiEvaluationAttributesRoute: ApiEvaluationAttributesRoute,
  ApiRegulationStandardsRoute: ApiRegulationStandardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
